/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alvinda Akbar
 */
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.util.Locale;
import java.text.SimpleDateFormat;
import java.util.Date;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
public class Daftar_pinjaman extends javax.swing.JFrame {
    SimpleDateFormat format_tanggal = new SimpleDateFormat("yyy-MM-dd");
    private int index;
    private String nourut;
    private String noanggota;
    private String namaanggota;
    private String judul_buku;
    private String tanggal_pinjam;
    private String lama_pinjam;
    private String status;
    

     public void LoadTable(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("NO_URUT");
        model.addColumn("NO_ANGGOTA");
        model.addColumn("NAMA_ANGGOTA");
        model.addColumn("JUDUL_BUKU");
        model.addColumn("TANGGAL_PINJAM");
        model.addColumn("LAMA_PINJAM");
        model.addColumn("STATUS");
        
         try {
//            int no = 1;
            String sql = "SELECT * FROM daftar_pinjaman";
            java.sql.Connection conn = (Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString("id"), 
                res.getString("NO_URUT"), res.getString("NO_ANGGOTA"), 
                res.getString("NAMA_ANGGOTA"), res.getString("JUDUL_BUKU"),res.getString(6), 
                res.getString(7), res.getString("STATUS")});
            }
            TblDataPinjaman.setModel(model);
        } catch (Exception e){
            
        }
    }
     
     public void ClearIsian(){
        TxtNoUrut.setText(null);
        TxtNoAnggota.setText(null);
        TxtNamaAnggota.setText(null);
        TxtJudulBuku.setText(null);
        TglPinjam.setDate(null);
        CmbStatus.setSelectedIndex(0);
        TxtHari.setText(null);
    }
    
    
    public Daftar_pinjaman() {
        initComponents();
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNoUrut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtNoAnggota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtNamaAnggota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtJudulBuku = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtHari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CmbStatus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        BtnEdit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        BtnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDataPinjaman = new javax.swing.JTable();
        TglPinjam = new com.toedter.calendar.JDateChooser();
        BtnPRINT = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DAFTAR PINJAMAN");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NO URUT");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NO ANGGOTA");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NAMA ANGGOTA");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("JUDUL BUKU");

        TxtJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJudulBukuActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("TANGGAL PINJAM");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("LAMA PINJAM");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("STATUS");

        CmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PINJAM", "KEMBALI", " " }));

        BtnTambah.setBackground(new java.awt.Color(102, 255, 255));
        BtnTambah.setForeground(new java.awt.Color(0, 0, 0));
        BtnTambah.setText("TAMBAH");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnEdit.setBackground(new java.awt.Color(102, 255, 255));
        BtnEdit.setForeground(new java.awt.Color(0, 0, 0));
        BtnEdit.setText("EDIT");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(102, 255, 255));
        BtnDelete.setForeground(new java.awt.Color(0, 0, 0));
        BtnDelete.setText("HAPUS");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        TblDataPinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "NO URUT", "NO ANGGOTA", "NAMA ANGGOTA", "JUDUL BUKU", "TANGGAL PINJAM", "LAMA PINJAM", "STATUS"
            }
        ));
        TblDataPinjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDataPinjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblDataPinjaman);

        TglPinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TglPinjamPropertyChange(evt);
            }
        });

        BtnPRINT.setBackground(new java.awt.Color(102, 255, 255));
        BtnPRINT.setForeground(new java.awt.Color(0, 0, 0));
        BtnPRINT.setText("PRINT");
        BtnPRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPRINTActionPerformed(evt);
            }
        });

        BtnBack.setBackground(new java.awt.Color(0, 204, 204));
        BtnBack.setForeground(new java.awt.Color(0, 0, 0));
        BtnBack.setText("KEMBALI");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtNoUrut, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtJudulBuku)
                            .addComponent(TglPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(TxtHari)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(595, 595, 595)
                        .addComponent(CmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnTambah)
                                .addGap(97, 97, 97)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnEdit)
                                .addGap(101, 101, 101)
                                .addComponent(BtnDelete)
                                .addGap(72, 72, 72)
                                .addComponent(BtnPRINT))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(116, 116, 116)
                                .addComponent(jLabel12))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNoUrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(TxtHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(TxtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnDelete)
                            .addComponent(BtnPRINT)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnTambah)
                            .addComponent(BtnEdit))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnBack)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        try {
            String sql = "INSERT INTO daftar_pinjaman "
                     + "VALUES (null,'" + TxtNoUrut.getText()+"',"
                    + "'" + TxtNoAnggota.getText()+"','"+TxtNamaAnggota.getText()+"','"
                    +TxtJudulBuku.getText()+"','"+tanggal_pinjam+"','"+TxtHari.getText()+"','"+CmbStatus.getSelectedItem()+"')";
            System.out.println(sql);
            java.sql.Connection conn = (Connection)Koneksi.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            LoadTable();
            ClearIsian();
            JOptionPane.showMessageDialog(null, "Data berhasil di tambah!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal ditambah!"+e.getMessage());
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void TxtJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtJudulBukuActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
         try {
            String sql = "UPDATE daftar_pinjaman SET NO_URUT = '" + TxtNoUrut.getText()    +
            "', NO_ANGGOTA = '" + TxtNoAnggota.getText() +   "', NAMA_ANGGOTA = '"    +
            TxtNamaAnggota.getText()+"', JUDUL_BUKU = '" + 
             TxtJudulBuku.getText()+"',TANGGAL_PINJAM = '"   +   tanggal_pinjam   + "',LAMA_PINJAM = '" + TxtHari.getText() + "', STATUS = '" + CmbStatus.getSelectedItem() +
                      "' WHERE  NO_URUT  = '" + TxtNoUrut.getText()+"'";
            System.out.println(sql);
            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.execute();
            LoadTable();
            ClearIsian();
            JOptionPane.showMessageDialog(null, "Data berhasil di edit");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Perubahan Data gagal!"+e.getMessage());
        }               
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        try {
            String sql = "DELETE FROM daftar_pinjaman WHERE NO_URUT = '"+TxtNoUrut.getText()+"'";
            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            LoadTable();
            ClearIsian();
            JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void TblDataPinjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDataPinjamanMouseClicked
        index = TblDataPinjaman.getSelectedRow();
        
        nourut = (String) TblDataPinjaman.getValueAt(index, 1);
        
        noanggota = (String) TblDataPinjaman.getValueAt(index, 2);
        namaanggota = (String) TblDataPinjaman.getValueAt(index, 3);
        judul_buku = (String) TblDataPinjaman.getValueAt(index, 4);
        tanggal_pinjam = (String) TblDataPinjaman.getValueAt(index, 5);
        lama_pinjam = (String) TblDataPinjaman.getValueAt(index, 6);
        status = (String) TblDataPinjaman.getValueAt(index, 7);
         
        TxtNoUrut.setText(nourut);
        TxtNoAnggota.setText(noanggota);
        TxtNamaAnggota.setText(namaanggota);
        TxtJudulBuku.setText(judul_buku);
        CmbStatus.setSelectedIndex(index);
        TxtHari.setText(lama_pinjam);
        
        try {
            SimpleDateFormat tgl1 = new SimpleDateFormat("yyyy-MM-dd");
            Date dt = format_tanggal.parse(tanggal_pinjam);
            tgl1.format(dt);
            TglPinjam.setDate(dt);
        } catch(Exception ex){
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_TblDataPinjamanMouseClicked

    private void TglPinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TglPinjamPropertyChange
        if (TglPinjam.getDate() != null) {
            tanggal_pinjam = format_tanggal.format(TglPinjam.getDate());
        }
    }//GEN-LAST:event_TglPinjamPropertyChange

    private void BtnPRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPRINTActionPerformed
        try {
            File namafile = new File("src/LaporanPinjaman.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, Koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_BtnPRINTActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
       dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_pinjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnPRINT;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JComboBox<String> CmbStatus;
    private javax.swing.JTable TblDataPinjaman;
    private com.toedter.calendar.JDateChooser TglPinjam;
    private javax.swing.JTextField TxtHari;
    private javax.swing.JTextField TxtJudulBuku;
    private javax.swing.JTextField TxtNamaAnggota;
    private javax.swing.JTextField TxtNoAnggota;
    private javax.swing.JTextField TxtNoUrut;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
