
import java.sql.Connection;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
public class form_login extends javax.swing.JFrame {
    
    int xx, xy;
    
    /**
     * Creates new form form_login
     */
    public form_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        Txt_Email = new javax.swing.JTextField();
        Txt_Password = new javax.swing.JPasswordField();
        Btn_Login = new javax.swing.JButton();
        jcshow_password = new javax.swing.JCheckBox();
        Icon_user = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_30px_3.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("PERPUSTAKAAN WAWASAN LUAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo_Login.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        Txt_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 30));

        Txt_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 190, 30));

        Btn_Login.setBackground(new java.awt.Color(0, 102, 255));
        Btn_Login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Login.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Login.setText("LOGIN");
        Btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, 30));

        jcshow_password.setText("Show Password");
        jcshow_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcshow_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(jcshow_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        Icon_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_customer_52px.png"))); // NOI18N
        getContentPane().add(Icon_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        MainView n = new MainView();
        dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void Txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_EmailActionPerformed

    private void Txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_PasswordActionPerformed

    private void jcshow_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcshow_passwordActionPerformed
        // TODO add your handling code here:
        if(jcshow_password.isSelected()){
            Txt_Password.setEchoChar((char)0);
        }
        else{
            Txt_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jcshow_passwordActionPerformed

    private void Btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LoginActionPerformed
        
        try{
           java.sql.Connection conn = (Connection) Koneksi.getConnection();
           java.sql.Statement stat = conn.createStatement();
           java.sql.ResultSet result=stat.executeQuery ("select * from tabel_user where " + "email='" +Txt_Email.getText()+"'");

           if(Txt_Email.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan Isi Email!");
           }
           else if(Txt_Password.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan Isi Password!");
           }
           else if (result.next()) {

                if (Txt_Password.getText().equals(result.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Login Berhasil");
                    String status = result.getString("Role");
                    if(status.equals("Pustakawan")){
                        MainPustakawan.T_NAP.setText(result.getString(2));
                        MainPustakawan.T_NAMA.setText(result.getString(7));
                        MainPustakawan.T_NIK.setText(result.getString(6));
                        MainPustakawan.T_EMAIL.setText(result.getString(3));
                        MainPustakawan.T_PASS.setText(result.getString(4));
                        MainPustakawan.T_NoHp.setText(result.getString(8));
                        MainPustakawan.T_Alamat.setText(result.getString(9));
                        new MainPustakawan().setVisible(true);
                        dispose();
                    }
                    if(status.equals("Anggota")){
                        MainAnggota.T_NAP.setText(result.getString(2));
                        MainAnggota.T_NAMA.setText(result.getString(7));
                        MainAnggota.T_NIK.setText(result.getString(6));
                        MainAnggota.T_EMAIL.setText(result.getString(3));
                        MainAnggota.T_PASS.setText(result.getString(4));
                        MainAnggota.T_NoHp.setText(result.getString(8));
                        MainAnggota.T_Alamat.setText(result.getString(9));
                        new MainAnggota().setVisible(true);
                        dispose();          
                    }
                    this.dispose();
                } 
               else {
                    JOptionPane.showMessageDialog(rootPane,"Password Salah");
                    Txt_Password.setText("");
                    Txt_Email.requestFocus();
                }
           } else {
               JOptionPane.showMessageDialog(rootPane, "Email Atau Password Salah Silahkan Isi Kembali!!","Message",JOptionPane.ERROR_MESSAGE);
               Txt_Email.setText("");
               Txt_Password.setText("");
               Txt_Email.requestFocus();
           }
       } catch (Exception e){
           JOptionPane.showMessageDialog(rootPane, "Gagal");
       }
    }//GEN-LAST:event_Btn_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Login;
    private javax.swing.JLabel Icon_user;
    private javax.swing.JTextField Txt_Email;
    private javax.swing.JPasswordField Txt_Password;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcshow_password;
    // End of variables declaration//GEN-END:variables
}
