/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class form_register extends javax.swing.JFrame {
    
    int xx, xy;
    String Role = "Anggota";
    Statement st;
    ResultSet rs;

    /**
     * Creates new form form_register
     */
    public form_register() {
        initComponents();
        AutoNumber();
        Txt_NAP.setEnabled(false);
    }
    
    private void AutoNumber(){
        try{
           java.sql.Connection conn = (Connection) Koneksi.getConnection();
           st = conn.createStatement();
           String sql = "SELECT max(right(NAP,4)) as no from tabel_user";
           rs=st.executeQuery(sql);
           if(rs.next()){
               String no_auto, nol_plus;
               int p;
               no_auto=Integer.toString(rs.getInt(1)+1);
               p = no_auto.length();
               nol_plus="";
               for (int i=1;i<=4-p;i++){
                   nol_plus = nol_plus + "0";
               }
               Txt_NAP.setText("NAP"+nol_plus+no_auto);
           }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Password = new javax.swing.JLabel();
        Txt_Password = new javax.swing.JTextField();
        Label_NIK = new javax.swing.JLabel();
        Label_Nama = new javax.swing.JLabel();
        Label_Alamat = new javax.swing.JLabel();
        Label_NoHp = new javax.swing.JLabel();
        Txt_NIK = new javax.swing.JTextField();
        Txt_Nama = new javax.swing.JTextField();
        Txt_NoHp = new javax.swing.JTextField();
        Jregister = new javax.swing.JButton();
        btn_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Icon_user = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_Alamat = new javax.swing.JTextArea();
        Txt_NAP = new javax.swing.JTextField();
        Txt_Email = new javax.swing.JTextField();
        Label_Email2 = new javax.swing.JLabel();
        Label_Email1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Password.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Label_Password.setForeground(new java.awt.Color(0, 102, 255));
        Label_Password.setText("Password");
        getContentPane().add(Label_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, 20));

        Txt_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 130, 20));

        Label_NIK.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Label_NIK.setForeground(new java.awt.Color(0, 102, 255));
        Label_NIK.setText("NIK");
        getContentPane().add(Label_NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        Label_Nama.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Label_Nama.setForeground(new java.awt.Color(0, 102, 255));
        Label_Nama.setText("Nama");
        getContentPane().add(Label_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        Label_Alamat.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Label_Alamat.setForeground(new java.awt.Color(0, 102, 255));
        Label_Alamat.setText("Alamat");
        getContentPane().add(Label_Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        Label_NoHp.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Label_NoHp.setForeground(new java.awt.Color(0, 102, 255));
        Label_NoHp.setText("NoHp");
        getContentPane().add(Label_NoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        Txt_NIK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Txt_NIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NIKActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, 20));

        Txt_Nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Txt_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, 20));

        Txt_NoHp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Txt_NoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NoHpActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_NoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 120, 20));

        Jregister.setBackground(new java.awt.Color(0, 102, 255));
        Jregister.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Jregister.setForeground(new java.awt.Color(255, 255, 255));
        Jregister.setText("Register");
        Jregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JregisterActionPerformed(evt);
            }
        });
        getContentPane().add(Jregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 150, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_30px_3.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("PERPUSTAKAAN WAWASAN LUAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 20));

        Icon_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_customer_52px.png"))); // NOI18N
        getContentPane().add(Icon_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        Txt_Alamat.setColumns(20);
        Txt_Alamat.setRows(5);
        Txt_Alamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jScrollPane1.setViewportView(Txt_Alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 330, 90));

        Txt_NAP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Txt_NAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NAPActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_NAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 130, 20));

        Txt_Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 130, 20));

        Label_Email2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Label_Email2.setForeground(new java.awt.Color(0, 102, 255));
        Label_Email2.setText("Email");
        getContentPane().add(Label_Email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, 20));

        Label_Email1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Label_Email1.setForeground(new java.awt.Color(0, 102, 255));
        Label_Email1.setText("NAP");
        getContentPane().add(Label_Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo_Register.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_PasswordActionPerformed

    private void Txt_NIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NIKActionPerformed

    private void Txt_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NamaActionPerformed

    private void Txt_NoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NoHpActionPerformed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        MainView n = new MainView();
        dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void JregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JregisterActionPerformed
        // TODO add your handling code here:
        try{
           if(Txt_NIK.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan Isi NIK Anda!");
           }
           else if(Txt_Nama.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan Isi Nama Anda!");
           }
           else if(Txt_NoHp.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan Isi Nomer Handphone!");
           }
           else if(Txt_Alamat.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan Isi Alamat Rumah Anda!");
           }
           else if(Txt_NAP.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan Isi Email Anda!");
           }
           else if(Txt_Password.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan Isi Password Anda!");
           }
           if(Txt_NIK.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan Isi NIK Anda!");
           }
           else
           {
               java.sql.Connection conn=(Connection)Koneksi.getConnection();
               st = conn.createStatement();
               String sqlA="SELECT * FROM tabel_user where NIK = '" +Txt_NIK.getText()+"'";
               rs=st.executeQuery(sqlA);
               
               if(rs.next())
               {
                   JOptionPane.showMessageDialog(null, "Data NIK telah terdaftar!");
               }
               else{
                   String sqlB = "INSERT INTO tabel_user VALUES (null, '" + Txt_NAP.getText() +"','"+ Txt_Email.getText() 
                +"','"+ Txt_Password.getText()+ "','" + Role + "','" + Txt_NIK.getText() + "','"
                + Txt_Nama.getText()+"','"+Txt_NoHp.getText()
                + "','" + Txt_Alamat.getText() + "')";
                conn=(Connection)Koneksi.getConnection();
                java.sql.PreparedStatement pst=conn.prepareStatement(sqlB);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registrasi Akun Berhasil");
                Txt_NIK.setText("");
                Txt_Nama.setText("");
                Txt_NoHp.setText("");
                Txt_Alamat.setText("");
                Txt_NAP.setText("");
                Txt_Email.setText("");
                Txt_Password.setText("");
                Txt_NAP.requestFocus();
                dispose();
               }
           } 
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
//        finally{
//            this.dispose();
//            form_login a = new form_login();
//            a.setVisible(true);
//        }
    }//GEN-LAST:event_JregisterActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
       
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void Txt_NAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NAPActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NAPActionPerformed

    private void Txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_EmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon_user;
    private javax.swing.JButton Jregister;
    private javax.swing.JLabel Label_Alamat;
    private javax.swing.JLabel Label_Email1;
    private javax.swing.JLabel Label_Email2;
    private javax.swing.JLabel Label_NIK;
    private javax.swing.JLabel Label_Nama;
    private javax.swing.JLabel Label_NoHp;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JTextArea Txt_Alamat;
    private javax.swing.JTextField Txt_Email;
    private javax.swing.JTextField Txt_NAP;
    private javax.swing.JTextField Txt_NIK;
    private javax.swing.JTextField Txt_Nama;
    private javax.swing.JTextField Txt_NoHp;
    private javax.swing.JTextField Txt_Password;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
